name: Publish 'Tree' component NuGet package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - run: dotnet pack -c Release -o ./drop ./src/TreeComponent/TreeComponent.csproj

    - run: dotnet nuget push ./drop/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://www.nuget.org
